---

- name: jdk folder creation
  file:
    path: /opt/jdk
    state: directory
    
- name: user creation
  user:
    name: "rafi"
    comment: "rafi"
    home: /opt/rafi

- name: OpenJdk 11 installation from source
  unarchive:
    src: https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz
    dest: /opt/jdk
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: copy jdk11 environment file to profile
  copy:
    src: jdk11.sh
    dest: /etc/profile.d/

- name: source jdk11 environment file
  shell: source /etc/profile.d/jdk11.sh

- name: java alternatives path installation
  command: alternatives --install /usr/bin/java java /opt/jdk/bin/java 2