---
- hosts: all
  connection: ssh
  gather_facts: True
  # remote_user: ec2-user
  become: yes

  tasks:
  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest

  roles:
    - java
    - tomcat