---
- hosts: all
  connection: ssh
  gather_facts: True
  become: yes

  tasks:
  - name: Update epel
    shell: amazon-linux-extras install epel -y

  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest

  - name: Install Apache
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Install MySQL
    ansible.builtin.yum:
      name: https://dev.mysql.com/get/mysql80-community-release-el7-5.noarch.rpm
      state: present

  - name: Install MySQL Community Server
    ansible.builtin.yum:
      name: https://dev.mysql.com/get/mysql80-community-release-el7-5.noarch.rpm
      state: present

  - name: Start and Enable mysql sever
    systemd:
      name: mysqld
      state: restarted
      enabled: true




  